name: Deploy Static Web App to Azure Web App - tara-fe-integrated

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for requesting the JWT
      contents: read # Required for actions/checkout

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E4707AF6EA094459A2A5F451075FFE7D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B12CB94D1B65442E826150D5E29BD3B2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FC7F373AC4D14A79AB65ABD3B5786507 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'tara-fe-integrated'
          package: .
          clean: true
